name: "8.4"

on:
  push:
  schedule:
    - cron: '15 3 * * 1'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push brabholdsa/php-dev:8.4-cli
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PHP_BASE_IMAGE=brabholdsa/php:8.4-cli
            PHP_VERSION=8.4
            NODE_VERSION=22.15.0
          push: true
          tags: brabholdsa/php-dev:8.4-cli

      - name: Build and push brabholdsa/php-dev:8.4-cli-imagick
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PHP_BASE_IMAGE=brabholdsa/php:8.4-cli-imagick
            PHP_VERSION=8.4
            NODE_VERSION=22.15.0
          push: true
          tags: brabholdsa/php-dev:8.4-cli-imagick

      - name: Build and push brabholdsa/php-dev:8.4-apache
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PHP_BASE_IMAGE=brabholdsa/php:8.4-apache
            PHP_VERSION=8.4
            NODE_VERSION=22.15.0
          push: true
          tags: brabholdsa/php-dev:8.4-apache

      - name: Build and push brabholdsa/php-dev:8.4-apache-imagick
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PHP_BASE_IMAGE=brabholdsa/php:8.4-apache-imagick
            PHP_VERSION=8.4
            NODE_VERSION=22.15.0
          push: true
          tags: brabholdsa/php-dev:8.4-apache-imagick
